// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyDVaDcM6tFP-ecZCdu33wSVQQfxumdlA',
    appId: '1:628935225637:web:a75a2d92a1c05368aeeacc',
    messagingSenderId: '628935225637',
    projectId: 'collectable-app-2026',
    authDomain: 'collectable-app-2026.firebaseapp.com',
    storageBucket: 'collectable-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLiOk4pT_24IQxjap3fTSUKs1gqE-MEeI',
    appId: '1:628935225637:android:db6b180ddc3b957faeeacc',
    messagingSenderId: '628935225637',
    projectId: 'collectable-app-2026',
    storageBucket: 'collectable-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ceIj88hYT69loiWgLKsws-fbqxEiwp8',
    appId: '1:628935225637:ios:262198c8c618668eaeeacc',
    messagingSenderId: '628935225637',
    projectId: 'collectable-app-2026',
    storageBucket: 'collectable-app-2026.firebasestorage.app',
    iosClientId: '628935225637-93jun7luf7gv45f3ce3qgi917k2hh8fh.apps.googleusercontent.com',
    iosBundleId: 'com.example.collectable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ceIj88hYT69loiWgLKsws-fbqxEiwp8',
    appId: '1:628935225637:ios:262198c8c618668eaeeacc',
    messagingSenderId: '628935225637',
    projectId: 'collectable-app-2026',
    storageBucket: 'collectable-app-2026.firebasestorage.app',
    iosClientId: '628935225637-93jun7luf7gv45f3ce3qgi917k2hh8fh.apps.googleusercontent.com',
    iosBundleId: 'com.example.collectable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyDVaDcM6tFP-ecZCdu33wSVQQfxumdlA',
    appId: '1:628935225637:web:be43db9af2638a8aaeeacc',
    messagingSenderId: '628935225637',
    projectId: 'collectable-app-2026',
    authDomain: 'collectable-app-2026.firebaseapp.com',
    storageBucket: 'collectable-app-2026.firebasestorage.app',
  );
}
