// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLrEbDqk9oNbhKbIJdBUnWRjJyGX8dm14',
    appId: '1:134199368025:web:0a2e0550e225472d5c5448',
    messagingSenderId: '134199368025',
    projectId: 'collectable-87df4',
    authDomain: 'collectable-87df4.firebaseapp.com',
    storageBucket: 'collectable-87df4.firebasestorage.app',
    measurementId: 'G-ZJ9R3T8H57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_U2AtH4moi4fD8JJrat3QWVgqVPmNKP8',
    appId: '1:134199368025:android:646c6556de26bccc5c5448',
    messagingSenderId: '134199368025',
    projectId: 'collectable-87df4',
    storageBucket: 'collectable-87df4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCajYfXCYEruSFRVNNFrvlgyEfxb8T8ERA',
    appId: '1:134199368025:ios:9efa6bfbf00768b65c5448',
    messagingSenderId: '134199368025',
    projectId: 'collectable-87df4',
    storageBucket: 'collectable-87df4.firebasestorage.app',
    iosBundleId: 'com.example.collectable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCajYfXCYEruSFRVNNFrvlgyEfxb8T8ERA',
    appId: '1:134199368025:ios:9efa6bfbf00768b65c5448',
    messagingSenderId: '134199368025',
    projectId: 'collectable-87df4',
    storageBucket: 'collectable-87df4.firebasestorage.app',
    iosBundleId: 'com.example.collectable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLrEbDqk9oNbhKbIJdBUnWRjJyGX8dm14',
    appId: '1:134199368025:web:737883164eba617b5c5448',
    messagingSenderId: '134199368025',
    projectId: 'collectable-87df4',
    authDomain: 'collectable-87df4.firebaseapp.com',
    storageBucket: 'collectable-87df4.firebasestorage.app',
    measurementId: 'G-M89GP333BQ',
  );

}